FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine3.20 AS build
WORKDIR /src

COPY enquetix.sln ./
COPY enquetix/*.csproj enquetix/
COPY enquetix.Test/*.csproj enquetix.Test/

RUN dotnet restore enquetix.sln

COPY enquetix/ ./enquetix/

WORKDIR /src/enquetix

RUN dotnet publish -c Release -o /app/publish

# Runtime final
FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine3.20 AS final
WORKDIR /app
COPY --from=build /app/publish .

RUN apk add wait4x

EXPOSE 5261
CMD ["wait4x", "tcp", "rabbitmq:5672", "-t", "30s", "--", "dotnet", "enquetix.dll"]